### ISSUE TITLE
[Proposal] Reorder items in boot menu

### ISSUE THREAD

**Issue by blacknomad** [manjaro/grub-theme#2]
As is the boot is ordered like this

* Timezone
* Keytable
* Lang
* Driver
* Boot

It might be a matter of taste but wouldn't this order be more logical?

* Language
* Keytable
* Timezone
* Driver
* Boot

```
function boot_menu {
    if [ "${hwclock}" = "utc=yes" ]; then
        class="utc"
        title="utc"
        clockset=""
    elif [ "${timezone}${bootlang}" = "" ]; then
        class="unset"
        title="utc"
        clockset=""
    else
        title="${def_timezone}"
        class="tz.${def_timezone}"
        clockset="utc=yes"
    fi
    min2d="$MINUTE"
    if regexp '(^.$)' "$min2d"; then
        min2d="0${min2d}"
    fi
    hour2d="$HOUR"
    if regexp '(^.$)' "$hour2d"; then
        hour2d="0${hour2d}"
    fi
    menuentry --class=tz.$class --hotkey=u "$hour2d:$min2d $title" "$clockset" {
        hwclock="$2"
        menu_reload
    }
    show_languages
    show_keymaps
    show_timezones
    show_drivers
    default=1
}
```

**Comment by fhdk** [comment]
Just forgot which account I was logged in with.
I take responsibility for the above proposal.

**Comment by excalibur1234** [comment]
i think they put timezone (almost) at the top, because the time is displayed at the top.
in that regard, i agree with its position.

but i have other concerns about the grub boot menu as listed in https://github.com/manjaro/release-plan/issues/125#issuecomment-292001533

**Comment by NuLogicSystems** [comment]
I find the this new grub boot menu not very intuitive for a new user, it can be hard to see initially how to proceed. Maybe something more like Ubuntu does for the modifiers (language, timezone, keymap, and driver) lined up along the bottom with only the kernel or boot portion in the main menu would make it easier for new users to understand.

**Comment by philmmanjaro** [comment]
@fhdk: please create a PR for it. I'll close this one. If still needed to be tracked, please open a [new issue](https://bugs.manjaro.org).
